(function(c){var d=window.AmazonUIPageJS||window.P,h=d._namespace||d.attributeErrors,f=h?h("ShareWidgetTriggerAssets",""):d;f.guardFatal?f.guardFatal(c)(f,window):f.execute(function(){c(f,window)})})(function(c,d,h){c.now("tafShareOnNetwork").execute(function(f){"undefined"!==typeof f?c.log("tafShareOnNetwork is already registered","WARN","ShareWidgetTriggerAssets"):c.when("A","socialShareUtil").register("tafShareOnNetwork",function(f,b){var d={facebook:{shareEndpoint:"https://www.facebook.com/dialog/share",
params:function(a){return{href:b.decodeEntities(a.url),display:"popup",quote:a.quote?b.decodeEntities(a.quote):"",app_id:"465632727431967"}},ref:"fb",height:450,width:700,isWebShare:!0},pinterest:{shareEndpoint:"https://www.pinterest.com/pin/create/button",params:function(a){return{url:b.decodeEntities(a.url),media:b.decodeEntities(a.image),description:b.decodeEntities(a.description)}},ref:"pi",height:620,width:700,isWebShare:!0},line:{shareEndpoint:"https://social-plugins.line.me/lineit/share",params:function(a){var e=
b.decodeEntities(a.title)+" "+b.decodeEntities(a.description);a=b.decodeEntities(a.url);return{text:e,url:a}},ref:"li",height:620,width:700,isWebShare:!0},twitter:{shareEndpoint:"https://twitter.com/intent/tweet",params:function(a){var e=b.decodeEntities(a.title);a=b.decodeEntities(a.url);if(e){var g=a?Math.min(a.length,20):-1;200<e.length+g+1&&(e=e.substring(0,200-(g+1+3))+"...")}return{text:e,url:a}},ref:"tw",height:470,width:670,isWebShare:!0},email:{shareEndpoint:"mailto:",params:function(a){return{subject:b.decodeEntities(a.title),
body:b.decodeEntities(a.description)+"\n"+b.decodeEntities(a.url)}},ref:"em",isWebShare:!1},sms:{shareEndpoint:"sms:",params:function(a){return{body:b.decodeEntities(a.title)+" "+b.decodeEntities(a.url)}},ref:"sm",isWebShare:!1},whatsapp:{shareEndpoint:"whatsapp://send",params:function(a){return{text:b.decodeEntities(a.title)+"\n"+b.decodeEntities(a.description)+"\n"+b.decodeEntities(a.url)}},ref:"wa",isWebShare:!1}};return{share:function(a,e){var g=d[e];if("undefined"===typeof g)b.logFatal("Unsupported network:"+
e,a.clientRef);else{var l=b.generateReftags(a,g.ref);a.url=b.updateReftagParam(a.url,l.returnReftag);b.logReftag(l.clickReftag);b.logCounter("Click."+g.ref,1);a=b.buildUrl(g.shareEndpoint,g.params(a),a.devicename,e);b.triggerShare(a,g.isWebShare,g.width,g.height)}}}})});c.when("A","tafShareOnNetwork","socialShareUtil","ready").execute(function(f,d,b){b.logCounter("Render",1);f.declarative("swf-share-network","click",function(c){c=c.data;var a=c.pageStateId,e=f.state(a);"undefined"===typeof e?b.logFatal("Page state:"+
a+" undefined"):d.share(e,c.network)});b.stopTimer()});c.when("A","tafBottomSheet","socialShareUtil","ready").execute(function(d,c,b){b.logCounter("Click.ShareIcon",1);d.declarative("swf-share-network-v2-icon","click",function(b){c.showBottomSheet()})});c.when("A").register("socialShareUtil",function(f){function k(){for(var e="",a=0;13>a;a++)e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return e}function b(e){return"undefined"!==typeof e.pageLevelStateKey?
f.state(e.pageLevelStateKey):e.pageLevelData}function h(e,a){d.ue&&(e="SocialShareJS."+e,d.ue.count(e,(d.ue.count(e)||0)+a))}function a(){d.uet&&d.uet("bb","SocialShareJS",{wb:1})}a();return{buildUrl:function(e,a,b,d){a=a||{};d=Object.keys(a);b=0<d.length&&("sms:"!==e||"IPHONE"!==b)?"?":"";for(var c=0;c<d.length;c++)"?"!==b&&(b+="\x26"),a[d[c]]&&(b+=d[c]+"\x3d"+encodeURIComponent(a[d[c]]));return e+b},logFatal:function(a,b){h("Fatal",1);var d="SHARE_WITH_FRIENDS_JS_WIDGET";b&&(d=d+"_"+b);c.log(a,
"FATAL",d)},decodeEntities:function(a){var b=document.createElement("textarea");b.innerHTML=a;return b.value},getPageData:b,generateReftags:function(a,d){var c,f;a=b(a);"undefined"!==typeof a&&(c=a.clientRef,f=a.deviceTypeRef);c=c?c:"un";f=f?f:"un";a=d?d:"un";d=k();a="cm_sw_"+a;c=c+"_"+f+"_"+d;return{returnReftag:a+"_r_"+c,clickReftag:a+"_c_"+c}},updateReftagParam:function(a,b){var d=/([?&/])ref_?=.*?(&|$)/i,c=-1!==a.indexOf("?")?"\x26":"?";a=a.match(d)?a.replace(d,"$1ref\x3d"+b+"$2"):a+c+"ref\x3d"+
b;return a},generateUUID:k,triggerShare:function(a,b,c,f){if(b){b=screen.width;var h=screen.height;c=c?c:.7*b;f=f?f:.7*h;d.open(a,"_blank","toolbar\x3d0,status\x3d0,width\x3d"+c+",height\x3d"+f+",top\x3d"+(h/2-f/2)+",left\x3d"+(b/2-c/2))}else d.open(a,"_top")},logReftag:function(a){f.ajax("/gp/aw/social/swf/metrics.html/ref\x3d"+a,{method:"post"})},logCounter:h,startTimer:a,stopTimer:function(){d.uet&&d.uet("be","SocialShareJS",{wb:1});d.uex&&d.uex("ld","SocialShareJS",{wb:1})}}});c.when("a-sheet").register("tafBottomSheet",
function(c){return{showBottomSheet:function(){var d=c.create({name:"cancelButtonSheet",height:400,closeType:"icon"});c.showSheet(d)}}})});